(deffunction loadRules()
	(load "Rules/01EstablecerCumplimientoDelCriterioA.clp")
	(load "Rules/02EstablecerEfectoDeSustanciasOEnfermedadesPrevias.clp")
	(load "Rules/03EstablecerSintomasEsquizofrenia.clp")
	(load "Rules/04EstablecerEsquizofreniaTipoParanoide.clp")
	(load "Rules/05EstablecerEsquzofreniaTipoCatatonico.clp")
	(load "Rules/06EstablecerEsquizofreniaTipoDesorganizado.clp")
	(load "Rules/07EstablecerEsquizofreniaTipoIndiferenciado.clp")

	(load "Rules/08EstablecerEsquizofreniaTipoResidual.clp")
	(load "Rules/09EstablecerTrastornoEsquizofreniforme.clp")
	(load "Rules/10EstablecerTrastornoEsquizoafectivo.clp")
	(load "Rules/11EstablecerTrastornoDelirante.clp")
	(load "Rules/12EstablecerTrastornoPsicoticoBreve.clp")
	(load "Rules/13EstablecerTrastornoPsicoticoCompartido.clp")
	(load "Rules/14EstablecerTrastornoPsicoticoDebidoAEnfermedad.clp")
	(load "Rules/15EstablecerTrastornoDebidoASustancias.clp")
)
