(deffunction loadRules()
	(load "Rules/1EstablecerCumplimientoDelCriterioA.clp")
	(load "Rules/2EstablecerEfectoDeSustanciasOEnfermedadesPrevias.clp")
	(load "Rules/3EstablecerSintomasEsquizofrenia.clp")
	(load "Rules/4EstablecerEsquizofreniaTipoParanoide.clp")
	(load "Rules/5EstablecerEsquzofreniaTipoCatatonico.clp")
	(load "Rules/6EstablecerEsquizofreniaTipoDesorganizado.clp")
	(load "Rules/7EstablecerEsquizofreniaTipoIndiferenciado.clp")
)
