(deffunction loadTemplates()
	(load "Templates/Curso.clp")
	(load "Templates/Esquizofrenia.clp")
	(load "Templates/Paciente.clp")
	(load "Templates/Psicotico.clp")
	(load "Templates/Sintomas.clp")
	(load "Templates/TipoCatatonico.clp")
	(load "Templates/TipoDesorganizado.clp")
	(load "Templates/TipoIndiferenciado.clp")
	(load "Templates/TipoParanoide.clp")
	(load "Templates/TipoResidual.clp")
)
