(deftemplate Paciente
(field Fase)
(field Duracion)
(field PoseeTrastorno)
(field Enfermedad)
(field TipoEnfermedadMedica)
(field Drogas)
(multifield TipoDroga)
(field EfectoExcesivo)
(field Limpio)
(field CumpleCriterioA)
)
