(deftemplate Sintomas
(field IdeasDelirantes)
(field TipoIdeasDelirantes)
(field Alucinaciones)
(field Episodio)
(field LenguajeDesorganizado)
(field ComportamientoCatatonico)
(field ComportamientoDesorganizado)
(field SintomasNegativos)
(field CantidadSintomas)
(field TratadoConExito)
(field DuracionSintoma)
(field DisfuncionSocial)
(field EpisodiosAnimicos)
(field DuracionEpisodio)
(field TrastornoDesarrollo)
(field Atenuados)
(field AplanamientoAfectivo)
)


